// Mocks generated by Mockito 5.4.4 from annotations
// in keep_mindful/test/app/screens/language/language_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:keep_mindful/features/bluetooth/bluetooth.dart' as _i5;
import 'package:keep_mindful/features/language/app_language.dart' as _i4;
import 'package:keep_mindful/features/language/app_language_notifier.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppLanguageNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLanguageNotifier extends _i1.Mock
    implements _i2.AppLanguageNotifier {
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void fetchLanguage() => super.noSuchMethod(
        Invocation.method(
          #fetchLanguage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> updateLanguage(_i4.AppLanguage? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLanguage,
          [language],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDevice(_i5.KeepMindfulDevice? newDevice) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevice,
          [newDevice],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
