include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    file_names: true
    flutter_style_todos: true
    no_logic_in_create_state: true
    prefer_asserts_with_message: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_in_for_each: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    sort_pub_dependencies: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    use_string_buffers: true
    valid_regexps: true

    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: false
    package_api_docs: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_setters_to_change_properties: true
    use_string_splits: true
    use_to_and_as_if_applicable: true
    void_checks: true
