// Mocks generated by Mockito 5.4.4 from annotations
// in keep_mindful/test/features/awakening/notifiers/wake_up_mode_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:keep_mindful/features/awakening/constants/constants.dart'
    as _i3;
import 'package:keep_mindful/features/awakening/repositories/wake_up_mode_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WakeUpModeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWakeUpModeRepository extends _i1.Mock
    implements _i2.WakeUpModeRepository {
  @override
  bool? getByMode(_i3.AlarmDisableMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #getByMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      ) as bool?);

  @override
  _i4.Future<void> setByMode(
    _i3.AlarmDisableMode? mode,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setByMode,
          [
            mode,
            enabled,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
