// Mocks generated by Mockito 5.4.4 from annotations
// in keep_mindful/test/app/shared/widgets/modal/modal_interval/modal_interval_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:keep_mindful/features/bluetooth/bluetooth.dart' as _i4;
import 'package:keep_mindful/features/timer/interval_notifier.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IntervalNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntervalNotifier extends _i1.Mock implements _i2.IntervalNotifier {
  @override
  Duration get interval => (super.noSuchMethod(
        Invocation.getter(#interval),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#interval),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.getter(#interval),
        ),
      ) as Duration);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setInterval(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #setInterval,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getInitialInterval() => super.noSuchMethod(
        Invocation.method(
          #getInitialInterval,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> saveInterval() => (super.noSuchMethod(
        Invocation.method(
          #saveInterval,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetInterval() => (super.noSuchMethod(
        Invocation.method(
          #resetInterval,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDevice(_i4.KeepMindfulDevice? newDevice) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevice,
          [newDevice],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
